---
title: "Analyze Alpha = 1"
author: "David Gerard"
date: "May 17, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Abstract

I simulated and fit the effects under an exchangeable $t$-statistic model. Nothing works well. I didn't run MOUTHWASH and BACKWASH with a variance inflation term because this term is non-identified.

# Analysis

I ran the simulations [here](https://github.com/dcgerard/ruvb_plus_ash/blob/master/code/exchangeable_mouthwash_sims.R) with methods coded up [here](https://github.com/dcgerard/ruvb_plus_ash/blob/master/code/non_nc_methods.R) and [here](https://github.com/dcgerard/ruvb_sims/blob/nc_var/Code/nc_adjustment_methods.R).

```{r}
library(tidyverse)
dat <- as_data_frame(readRDS("../output/alpha_1_sims_out/sims_out.RDS"))
pi0dat <- select(dat, nullpi, Nsamp, ncontrols, contains("pi0_")) %>%
  gather(key = "Method", value = "Pi0hat", contains("pi0_"))
pi0dat$Method <- stringr::str_replace(pi0dat$Method, "pi0_", "")
pl <- ggplot(data = pi0dat, mapping = aes(x = Method, y = Pi0hat)) +
  facet_grid(.~Nsamp) +
  geom_boxplot() +
  geom_hline(yintercept = 0.9) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5),
        strip.background = element_rect(fill = "white")) +
  ggtitle("pi0hat")
print(pl)
```

MOUTHWASH and BACKWASH have the best AUC, as usual.

```{r}
aucdat <- select(dat, nullpi, Nsamp, ncontrols, contains("auc_")) %>%
  gather(key = "Method", value = "auc", contains("auc_"))
aucdat$Method <- stringr::str_replace(aucdat$Method, "auc_", "")
pl <- ggplot(data = aucdat, mapping = aes(x = Method, y = auc)) +
  facet_grid(.~Nsamp) +
  geom_boxplot() +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5),
        strip.background = element_rect(fill = "white")) +
  ggtitle("auc")
print(pl)
```

```{r}
sessionInfo()
```
