---
title: "Home"
output:
  html_document:
    toc: false
---

## Simulations

* [RUVB Plus ASH Analysis](ruvb_plus_ash.html): I ran all the confounder adjustment methods when the true $\pi0$ is 0.9. Signal was added by poisson thinning. I then ran either ASH or qvalue on the resulting estimated effect sizes and their corresponding standard errors. Except for MOUTHWASH and BACKWASH, RUVB does the best.
* [Look at Calibration of LFDR/LFSR's](ruvb_lfsr.html) MOUTHWASH is awesome. RUVB + ASH is awesome. RUVB by itself is not so awesome.
* [Consistancy between seqgendiff and datamaker.R](compare_dg_seqgendiff.html)
* [Recapitulate AUC plots from paper using the output from seqgendiff.](initial_pvalue_eda.html)
* [Explore average FDR control of various methods](fdr_control.html)
* [Explore variability of FDR control of various methods](fdp_variability.html)
* [Explore variability in coverage results](coverage_variance.html). Don't see anything different here from what I have been seeing. Though it might be a little more clear.
* [When simulating under the assumed model, MOUTHWASH usually returns variance inflation factors less than 1.](vicar_t.html)
* [CATE does not adjust for df. This makes its variances very small for small sample sizes](var_code.html). Here, I also show equivalence between vicar's functions and cate and RUV4's functions.
* [Limma is scale-equivariant, recalculate limma-shrunk variances in RUV4 using three different approaches](limma_shrink.html)

# Paper Plots
* [AUC plot seems entirely done](ruvb_paper_plots.html).
* [Coverage plot needs more work](ruvb_paper_plots_coverage.html). In particular, I am afraid that I coded up the "c" methods incorrectly. I need to double check them.
* [Small difference between Gagnon-Bartsch variance inflation and my variance inflation](check_c_inflation.html). When I use the maximum-likelihood approach, this results in a small multiplicative difference that basically amounts to using `solve(crossprod(X))` vs `solve(crossprod(cbind(X, Z)))`.
* [Coverage plots looking at losses < 0.9 or > 0.975](coverage_try_2.html). RUVB is relatively stable under both losses and over all scenarios. This is not true of any other method.
* [With lots of boxplots, narrowed down best methods to RUVB, RUVBnn, RUV2, RUV2l, RUV3o, and RUV3la](ruvb_vs_all_boxplots.html). Other possibilities are CATEd and CATEdl.
* [Loss plots show same favorites as above.](ruvb_vs_all_lossplots.html)
* [Boxplots, loss plots, and median plots of just the best methods](ruvb_in_depth_best_methods.html). RUVB does best in terms of median coverage and for larger sample sizes it seems that RUVB might also do better when there are more control genes, but I need to test this.
* [Bootstrap confidence intervals for the losses.](ruvb_loss_boot.html) These are mixed results. Basically, it says that one should only use either RUVB or RUV2. Though, I think this is fine since RUV2 has much worse AUC.
* [MAD is not invariant](mad_not_equivariant.html).
* [I don't know if including the positive controls is worth it.](real_data_explore.html)
* [Mixed results when running best methods on Gagnon-Bartsch datasets](gb_output_analysis.html). Here, I looked at the number of positive controls at the top genes for all 5 datasets that GB used and using either spike-in's or housekeeping genes.

# alpha = 1
* [First try at $\alpha = 1$](alpha_1.html) No methods work well when I fit everything correctly assuming $\alpha = 1$. I did not run MOUTHWASH and BACKWASH with variance inflation because I hadn't implemented the variance inflation penalty yet to identify the model. Note that I ran all simulations when $\pi_0 = 0.1$ and the number of controls was 10.
* [Simulate under alpha = 1 but fit assuming alpha = 0](alpha_1_assume_0.html). Variance-scaled versions of BACKWASH and MOUTHWASH still work pretty darn well.
* [Using the correct level of `sprop` seems to help when we have the penalty](diff_sprop_varpen.html).

[rmarkdown]: http://rmarkdown.rstudio.com/rmarkdown_websites.htm
[rstudio]: https://www.rstudio.com/products/rstudio/download/preview/
